name: Waka Readme Stats

on:
  schedule:
    - cron: "30 18 * * *"

  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          COMMIT_MESSAGE: "Updated with Ho3ein"
          SHOW_SHORT_INFO: "False"
          SHOW_OS: "False"
          SHOW_AI_CODE_TIME: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_AI_CODING: "False"
          SHOW_COMMIT: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIME: "False"

          BAR_STYLE: "svg"
          BAR_RADIUS: "0"
